run-name: æ„å»º MkDocs-Material é¡µé¢å¹¶æ¨é€åˆ° gh-pages åˆ†æ”¯ ğŸš€

# ç»™å®šå·¥ä½œæµå°†æ„å»ºæ–‡æ¡£é¡µé¢ï¼Œé€‚ç”¨äº GitHub Actions
name: æ„å»º MkDocs-Material é¡µé¢å¹¶æ¨é€åˆ° gh-pages åˆ†æ”¯

# è¯¥å·¥ä½œæµåœ¨æ¨é€åˆ° main åˆ†æ”¯æ—¶è§¦å‘
on:
  push:
    branches:
      - main

# å·¥ä½œæµæƒé™ï¼Œå…è®¸å·¥ä½œæµå†™å…¥å†…å®¹
permissions:
  contents: write

jobs:
  # ç¬¬ä¸€ä¸ªå·¥ä½œï¼Œåç§°ä¸º Build MkDocs-Material é¡µé¢å¹¶æ¨é€åˆ° gh-pages åˆ†æ”¯
  build:
    name: æ„å»º MkDocs-Material é¡µé¢å¹¶æ¨é€åˆ° gh-pages åˆ†æ”¯
    # runs-on è¡¨ç¤ºè¿è¡Œåœ¨å“ªé‡Œï¼ŒæŒ‡ GitHub Actions æœåŠ¡å™¨çš„æ“ä½œç³»ç»Ÿï¼Œä½¿ç”¨æœ€æ–°ç‰ˆæœ¬çš„ ubuntu æ“ä½œç³»ç»Ÿ
    runs-on: ubuntu-latest
    # å·¥ä½œæµçš„æ­¥éª¤
    steps:
      - name: æ£€å‡ºå¹¶å…‹éš†ä»£ç åº“åˆ°è¿è¡Œç›®å½•
        # uses è¡¨ç¤ºä½¿ç”¨, ä½¿ç”¨ GitHub Actions å®˜æ–¹åº“çš„ checkout@v4 æ£€å‡ºä»£ç åº“
        uses: actions/checkout@v4
      - name: é…ç½® Git å‡­æ®ï¼Œç”¨äºæ¨é€åˆ° gh-pages åˆ†æ”¯
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: è®¾ç½® Python ç¯å¢ƒ
        # ä½¿ç”¨ GitHub Actions å®˜æ–¹åº“çš„ setup-python@v5 æ¥è®¾ç½® Python ç¯å¢ƒ
        uses: actions/setup-python@v5 
        with:
          python-version: '3.x'
      - name: å®‰è£… MkDocs-Material çš„ä¾èµ–é¡¹
        run: |
          pip install mkdocs-material
      - name: æ£€æŸ¥å½“å‰ç¯å¢ƒ pip å®‰è£…çš„æ‰€æœ‰åŒ…
        run: |
          pip list
      - name: æ„å»º MkDocs-Material é¡µé¢å¹¶æ¨é€åˆ° gh-pages åˆ†æ”¯
        run: |
          mkdocs gh-deploy --force
